version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: rental_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: rental_system
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: rental_flask
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=admin123
      - DB_NAME=rental_system
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: rental_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static
    depends_on:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rental_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=admin123
    depends_on:
      - db

volumes:
  mysql_data:
